Get PCI and MAC config data from the actual devices
redhat-partner-solutions/rhel-sriov-test pull request #145
Opened 2023-03-11 16:05 UTC by jianzzha

Currently we use testbed yaml to statically provide the PCI and MAC information for the PF. In stead of letting the tester manually provide these info (therefore error prone),  a better option is to let the script to get them from the actual devices at the test initialization phase. This is also more user friendly.

The only drawback is the  PCI and MAC util test function can not use the provisioned value as expected value, in stead, a pattern match is used for those function test.

2023-03-11 16:10 UTC, jianzzha commented
Full test report:
https://redhat-eets.github.io/pytest-reports/PR145.html

2023-03-17 20:05 UTC, jianzzha commented on sriov/tests/conftest.py
> +def settings(dut, trafficgen) -> Config:
@dkosteck This is the key change for this PR, basically the we add the required pci info here, so that we can keep the configtestdata unchanged

2023-03-17 20:06 UTC, jianzzha commented on sriov/tests/conftest.py
> +def settings(dut, trafficgen) -> Config:
@dkosteck and because the configtestdata didn't change, so the test case didn't change

2023-03-17 20:23 UTC, jianzzha commented on sriov/tests/common/test_utils.py
> +    assert re.match(r'^\w{4}:\w{2}:\w{2}', pf_pci)
@dkosteck this test we switch to pattern match

2023-03-17 20:24 UTC, jianzzha commented on sriov/tests/common/test_utils.py
> +    assert re.match(r'^\w{4}:\w{2}:\w{2}', vf_pci)
@dkosteck same thing here

2023-03-17 20:28 UTC, jianzzha commented
@akiselev1 @dkosteck This PR solved the same problem as Daniel's PR; this PR has a smaller change set, by keeping the configtestdata untouched, so that none of the test cases need to be modified (except the two functions tests are switched to pattern match). The may change is on the conftest - the settings fixture now take two parameters

2023-03-17 20:29 UTC, jianzzha commented
@dkosteck @akiselev1 by the way, this PR also remove the need to enter the mac address on trafficgen

2023-03-20 15:22 UTC, dkosteck requested changes
I think overall this looks good, my only request is the comment about return types.

2023-03-20 20:55 UTC, akiselev1 approved these changes
Looks good. I will kick off e2e-test-710 to have a complete coverage.

2023-03-21 19:41 UTC, merged